name: Python application

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at 00:00 UTC
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "${HOME}/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        uv venv .venv
        uv pip install ruff pytest
        if [ -f requirements.txt ]; then uv pip install -r requirements.txt; fi

    - name: Lint with Ruff
      run: |
        uv run ruff check .

    - name: Run main.py
      env:
        TOKEN: ${{ secrets.TOKEN }}
        PROFILE: ${{ secrets.PROFILE }}
      run: |
        uv run python main.py
